[project]
name = "chainpoll"
description = "Unique voting contract for project 09"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.chainpoll]
path = "contracts/chainpoll.clar"

[repl.analysis]
passes = ["check_checker"]
